### PR TITLE
move dependent: destroy to user model

### LINKED ISSUE #40: Add dependency to all the models connect with User
# REQUIREMENTS
Add dependency in the user model to the rest of the models.

# Acceptance Criteria
List all required acceptance criteria
- [ ] If you delete a user, his profile, skills, and social networks delete too.

### PR DESCRIPTION
**Pull request by DerekAyala**
# Description
What did you implement/Why did you implement this:
 - Fix dependent: destroy in skill, profile, social network models with the user model

### CODE REVIEW

**Review by AngelBFdev — APPROVED** [review]
LGTM

**Review by diegoOG09 — APPROVED** [review]
LGTM, but rubocop does not mark errors if you upload it without the "dependent" ?

**Review by BrandonVG — APPROVED** [review]
LGTM

**Review by JuanequeX — APPROVED** [review]
LGTM

**Review by xFerchoVJ — APPROVED** [review]

**Pull request merged**
